name: Swift

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  swift-test:
    strategy:
      matrix:
        include:
          - os: macos-10.15
            swift_version: 5.2
            xcode: /Applications/Xcode_11.7.app/Contents/Developer
          - os: macos-10.15
            swift_version: 5.3
            xcode: /Applications/Xcode_12.app/Contents/Developer
          - os: macos-11
            swift_version: 5.4
            xcode: /Applications/Xcode_12.5.app/Contents/Developer
          - os: macos-11
            swift_version: 5.5
            xcode: /Applications/Xcode_13.0.app/Contents/Developer
          - os: ubuntu-18.04
            swift_version: 5.4
          - os: ubuntu-20.04
            swift_version: 5.4
    name: Build on ${{ matrix.os }} with Swift ${{ matrix.swift_version }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test

  windows-test:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - uses: MaxDesiatov/swift-windows-action@v1
        with:
          shell-action: swift test
